on:
  gollum:
  workflow_dispatch:

jobs:
  update-gh-pages:
    name: Wiki Repo Cloning
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        name: Checkout repo
        with: 
          repository: Mathges/Mathges.github.io
          path: /docs
        run: git clone https://github.com/Mathges/Mathges.wiki.git 
