on:
  gollum
  workflow_dispatch:

jobs:
  update-gh-pages:
    name: Wiki Repo Cloning
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
        with: 
          repository: Mathges/Mathges.github.io
          path: /docs
      - name: Cloning wiki
        run: git clone https://github.com/Mathges/Mathges.wiki.git 
