name: Deploy Pages

on:
  push:
    branches:
      - 'Mathges-patch-1'

jobs:
  pre-build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      actions: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
            python-version: '3.10'
      - run: mkdir dist
      - run: python script.py
      - run: mv docs dist/docs
      - run: cp index.json dist/index.json
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  # build:
  # build with the index.json
  # For Ecla: build the list from index.json

  # deploy:
  # then deploy the pages
